name: Grzegorz Bułat
title: Grzegorz Bułat | A personal blog
description: C# Developer. Technology, gadgets, sport
tags:
  - blog
  - c#
  - csharp
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: grzegorz.bulat1@gmail.com
# See: https://disqus.com/
disqus_username: grzegorzbulat
# Contact Form Setting
# See: https://formspree.io/
# formspree_form_id: formspree_form_id
